#!/usr/bin/env zsh

/usr/bin/flatpak remote-add --system --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
/usr/bin/flatpak repair --system
/usr/bin/flatpak update --system -y --noninteractive
/usr/bin/flatpak uninstall --system --delete-data --unused -y --noninteractive
